### ISSUE TITLE
ENH: Saucelab integration

### ISSUE THREAD

**Issue by Abhimaniu** [pyqa/prodigyqa#11]
**Is your feature request related to a problem? Please describe.**
Need to integrate framework with sauce lab to run test cases on cloud platform. 

**Describe the solution you'd like**
- Create Sauce lab trial version account. 
- Sauce-python client to report job information to the Sauce Labs dashboard. 
- Configure desired capabilities to set the type of browser and OS that we will automate.
- Configure command executor to point to the Sauce cloud and use Sauce Labs authentication to log in.
- Sample test script which will make use of all above mentioned points for demo purpose.

**Comment by surevs** [comment]
@Abhimaniu : Please update or submit a PR in case you are done with the update
