### ISSUE TITLE
ENH - Implement selenium grid to achieve remote execution.

### ISSUE THREAD

**Issue by Abhimaniu** [pyqa/prodigyqa#6]
**Is your feature request related to a problem? Please describe.**
Need to implement selenium grid, to achieve remote execution of test cases across different browsers, operating systems and machines in parallel.

**Describe the solution you'd like**

- Use selenium standalone jar for creating hub and nodes.
- Configure desired capabilities to set the type of browser and OS that we will automate.
- Configure remote web driver to set which node (or machine) that our test will run against.
- Sample test script which will make use of all above mentioned points for demo purpose.

**Comment by surevs** [comment]
there are couple of changes made on folder structure. we shall revisit this one after the repo is a little stabilised
